apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment-api-1.yaml
  - deployment-api-2.yaml
  - service-api-1.yaml
  - service-api-2.yaml
  - route-api-1.yaml
  - route-api-2.yaml

patches:
  - target:
      kind: Route
      name: external-api-1
    patch: |-
      - op: replace
        path: /spec/host
        value: external-api-1.apps.cluster-bdvkn.bdvkn.sandbox980.opentlc.com
  - target:
      kind: Route
      name: external-api-2
    patch: |-
      - op: replace
        path: /spec/host
        value: external-api-2.apps.cluster-bdvkn.bdvkn.sandbox980.opentlc.com
